{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rematch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rematch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rematch/rematch_{{ version }}.tar.gz
  sha256: a409dec978cd02914cdddfedc974d9b45bd2975a124d8870d52cfd7d37d47578

build:
  merge_build_host: True  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('rematch')"           # [not win]
    - "\"%R%\" -e \"library('rematch')\""  # [win]

about:
  home: https://github.com/MangoTheCat/rematch
  license: MIT
  summary: A small wrapper on 'regexpr' to extract the matches and captured groups from the match
    of a regular expression to a character vector.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rematch
# Title: Match Regular Expressions with a Nicer 'API'
# Version: 1.0.1
# Author: Gabor Csardi
# Maintainer: Gabor Csardi <gcsardi@mango-solutions.com>
# Description: A small wrapper on 'regexpr' to extract the matches and captured groups from the match of a regular expression to a character vector.
# License: MIT + file LICENSE
# LazyData: true
# URL: https://github.com/MangoTheCat/rematch
# BugReports: https://github.com/MangoTheCat/rematch/issues
# RoxygenNote: 5.0.1.9000
# Suggests: covr, testthat
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2016-04-20 19:54:37 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2016-04-21 08:20:46
