travis:
  secure:
    BINSTAR_TOKEN: Ll3XnQArKGBoFV9IIYJC5rf7u90I8J+Hu77yx8r6v4H8+m7ADBusR6Pc4XAXRt2oSXMLo4fD4fRwhp5OTXHInXua0hL0/ZRspqR9dwMkNgDS3yw53rOBboqcklNg97D438buUDh53X6N/Yb8ipmTvigo/4wO9RIHF+xuS9P25rHvJiX+vMEfBN9a//V2pZ1TX6c4i7gHF26uRj6h5FmvMNoB2bgYR9K5sIbRQPBKyayUDpw6LjCKjHcb5lWt7NlwmXRK3KQPLrMfcBXeJ+f91PkcoixO1yQEJMEkJzA+S23pFO7FQenU/hXyt2DVmdWbMKK4LDn84BNSrrnbHXDvn2Er1Cj2PHtFtlLCrc70Y0jn9UVCFcWflvAX712cn3uFnHIx4TDH+Lb4NlI5QtHYwAnGvBQW5bXJahjIccjoc+OCQK1gmLliDyHOXxyLrM7MbJ49Zrttmf+uHkS5qTB4425NgK/gfLYwT53GgbZQ2Wp0VUIppm8lWBw5YQvsAKiyIGmLzjO00LxCntOJfgrFzjU3ddthpjBl4fRhKBY2cSrgXRAWAMV9mUoI+Sft90kfA58byHyWK95PRmI5DIRkIjPL9CuI7jx9GVIwd/Ffp7teZ89kA2ceMJ2hKjHrucLEi3jp1vqkicQEKBmw1abVjXWBNAZeRoMvhNbUi8hOSrI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
